### ISSUE TITLE
INSPEC: ESXI-70-000063 fails with no PortGroups set to VLAN 1 (Windows)

### ISSUE THREAD

**Issue by pbarrette** [vmware/dod-compliance-and-automation#126]
### Describe the bug

With no port groups containing VLAN 1 on any vSwitch, an inspec scan against ESXI-70-000063 fails if a VLAN includes the number 1.

### Reproduction steps

1. Ensure no port groups are set to VLAN 1 on ESXi.
2. Ensure at least one port group has a VLAN which includes the number 1. (eg 10 or 21)
3. Execute an inspec scan against control ESXI-70-000063

### Expected behavior

If no port groups are set to VLAN 1, the control should be marked as compliant.

### Additional context

Windows 2019, Powershell 5.1, Inspec 5.21.29

This appears to be a problem with Windows and CRLFs again.

I have corrected this by changing line 63 of "ESXI-70-000063" to read:
```
command = "$out = Get-VMHost -Name #{vmhost} | Get-VirtualPortGroup -Standard | Select-Object -ExpandProperty VlanId; $out.Replace(\"`r\",\"\")"
```

But again, I don't think this is necessarily the best solution.

**Comment by pstearns** [comment]
I addressed this by changing the inspec matcher from match to cmp. 

```
if !vmhosts.empty?
    vmhosts.each do |vmhost|
      command = "Get-VMHost -Name #{vmhost} | Get-VirtualPortGroup -Standard | Select-Object -ExpandProperty VlanId"
      describe powercli_command(command) do
        its('stdout.strip') { should_not cmp '1' }
      end
    end
  else
```
MATCH will look for patterns which will flag the 1.
CMP is for general use equality (inspec suggests trying it before using eq)

**Comment by rlakey** [comment]
Fixed all of the potential output differences between running this on Windows/Linux and/or Powershell/Powershell Core in https://github.com/vmware/dod-compliance-and-automation/commit/f5f30858d63189f45e0465617a3a28ec67769c64

**Comment by pbarrette** [comment]
This one is still failing.
There's 1 standard switch with a Portgroup on VLAN 21:
```
     [FAIL]  PowerCLI Command: Get-VMHost -Name esxiserver | Get-VirtualPortGroup -Standard | Select-Object -ExpandProperty VlanId stdout.strip is expected not to match "1"
     expected "0\r\n21" not to match "1"
     Diff:
     @@ -1,2 +1,3 @@
     -1
     +0
     +21
```
As noted by @pstearns, changing to `cmp` works.
